// <auto-generated />
using System;
using APIs_Tutorial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIs_Tutorial.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20210713094034_createlast")]
    partial class createlast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIs_Tutorial.Entities.ExamDetail", b =>
                {
                    b.Property<string>("Examvenue")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectFour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectThree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectTwo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Examvenue");

                    b.ToTable("ExamDetails");
                });

            modelBuilder.Entity("APIs_Tutorial.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
